# Generated by Django 3.1.5 on 2021-11-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=200)),
                ('departure_city', models.CharField(max_length=200)),
                ('arrival_city', models.CharField(max_length=200)),
                ('date_of_departure', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
