# Generated by Django 3.1.5 on 2021-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
